// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/assets/resume.pdf.asset.json
var resume_pdf_asset_default = {
  version: 1,
  asset_id: "c6bc7ac1-7bfe-44e2-b46f-71f2daf120d4",
  project_id: "f88209d2-1a32-46bc-87b7-5310c954502c",
  url: "/__l5e/assets-v1/c6bc7ac1-7bfe-44e2-b46f-71f2daf120d4/Jaikrishnan_Ganeshan_Resume.pdf",
  r2_key: "a/v1/f88209d2-1a32-46bc-87b7-5310c954502c/c6bc7ac1-7bfe-44e2-b46f-71f2daf120d4/Jaikrishnan_Ganeshan_Resume.pdf",
  original_filename: "Jaikrishnan_Ganeshan_Resume.pdf",
  size: 309378,
  content_type: "application/pdf",
  created_at: "2026-08-11T10:57:09Z"
};

// src/data/portfolio-data.ts
var portfolioData = {
  personal: {
    name: "Jaikrishnan Ganeshan",
    title: "Product Architect",
    tagline: "Building AI-driven physical & digital systems from first principles \u2014 across Robotics, AI, and Platform Products",
    location: "Hyderabad, India",
    phone: "+91 9840984314",
    email: "jaikrishnan1991@gmail.com",
    linkedin: "https://linkedin.com/in/jaikrishnanganeshan",
    resumeUrl: resume_pdf_asset_default.url,
    portfolioUrl: "https://docs.google.com/presentation/d/13UhZUHKB1PQhKN6eRoJE7jubAwtRd75e14L_6Z4uimU/export/pdf"
  },
  philosophy: [
    { text: "Product-centric leader with 10+ years of experience building complex technology products from first principles.", highlight: true },
    { text: "My approach begins with deep problem identification and user context, followed by structured product discovery, system architecture design, and iterative execution." },
    { text: "I specialize in converting ambiguous problem spaces into clear product narratives, scalable architectures, and intuitive user experiences \u2014 while remaining hands-on across technology, design, and delivery." }
  ],
  capabilities: [
    {
      title: "Problem Discovery & Strategy",
      icon: "compass",
      skills: [
        "User Research",
        "Problem Framing",
        "Jobs-to-be-Done",
        "Value Proposition Design",
        "Opportunity Sizing",
        "Product Vision",
        "Product Lifecycle"
      ]
    },
    {
      title: "Product Definition",
      icon: "layout",
      skills: [
        "PRDs",
        "User Journeys",
        "System Thinking",
        "MVP Scoping",
        "Trade-off Analysis",
        "Roadmapping",
        "Prioritization (RICE)",
        "AI Product Management",
        "GenAI Product Management",
        "Technical Product Management"
      ]
    },
    {
      title: "Product Architecture",
      icon: "boxes",
      skills: [
        "First-Principles Design",
        "Modular Architectures",
        "Hardware\u2013Software Co-design",
        "Platform Thinking",
        "API-First Systems"
      ]
    },
    {
      title: "Delivery & Scaling",
      icon: "rocket",
      skills: [
        "Agile Product Delivery",
        "Cross-functional Leadership",
        "Feedback-driven Iteration",
        "Design-for-Scale",
        "Reliability & Maintainability",
        "Scrum",
        "Waterfall",
        "Agile",
        "Project Management"
      ]
    },
    {
      title: "Technology Enablement",
      icon: "cpu",
      skills: [
        "AI Application Integration",
        "RAG-based Systems",
        "Embedded Systems",
        "Computer Vision",
        "Cloud-Native Platforms"
      ]
    }
  ],
  experience: [
    {
      id: "evochef",
      title: "Head of Product",
      company: "EvoChef LLP",
      location: "India",
      period: "Apr 2026 \u2013 Present",
      type: "leadership",
      summary: "Owning an IP-led smart appliance portfolio and its connected-platform strategy.",
      achievements: [
        "Own the end-to-end lifecycle of an IP-led smart appliance portfolio \u2014 discovery, architecture, MVP validation, launch and scale-up \u2014 across mechanical, firmware, IoT, cloud, AI and UX layers.",
        "Leading the shift from standalone appliances to a connected smart-kitchen ecosystem, turning telemetry into analytics, remote diagnostics and subscription monetisation.",
        "Govern external engineering partners and the business-systems stack; support the founder on Series A positioning and international expansion."
      ]
    },
    {
      id: "theknowledgehub",
      title: "Chief Technology Officer / Product Architect",
      company: "The Knowledge Hub",
      location: "Dubai / India (Remote)",
      period: "Mar 2025 \u2013 Present",
      type: "founder",
      summary: "Redesigning a legacy EdTech platform into an AI-native, outcome-driven learning ecosystem.",
      achievements: [
        "Reframed the product vision of a legacy EdTech platform by identifying core learner and educator pain points and realigning the platform around learning outcomes rather than features.",
        "Led end-to-end product discovery across learner journeys, content architecture, and platform modularity.",
        "Designed an AI-native product architecture enabling personalization while preserving pedagogical integrity.",
        "Established product-led execution practices, ensuring teams owned user outcomes instead of task delivery."
      ]
    },
    {
      id: "brane",
      title: "Solution Leader (Product & Systems)",
      company: "Brane Group",
      location: "Hyderabad, India",
      period: "Sep 2023 \u2013 Apr 2025",
      type: "leadership",
      summary: "Led product definition for robotics and medical systems in high-constraint environments.",
      achievements: [
        "Owned product definition for robotics and medical systems operating in high-constraint physical environments.",
        "Translated real-world operational problems into system-level architectures spanning sensors, embedded control, AI perception, and user interfaces.",
        "Acted as the product bridge between clients, engineering teams, and regulatory requirements."
      ]
    },
    {
      id: "rakaka",
      title: "Founder & Chief Executive Officer",
      company: "Rakaka Food Technology",
      location: "Chennai, India",
      period: "Dec 2018 \u2013 Aug 2023",
      type: "founder",
      summary: "Built and scaled a patented autonomous cooking platform from concept to pilot deployment.",
      achievements: [
        "Identified fundamental inefficiencies in commercial cooking workflows through ground-level observation and first-principles problem analysis.",
        "Conceived and built an autonomous cooking product from scratch \u2014 spanning mechanical design, embedded systems, software orchestration, and user experience.",
        "Led the complete product lifecycle: problem discovery \u2192 concept validation \u2192 MVP \u2192 iterative refinement \u2192 pilot-scale deployment.",
        "Designed a modular, scalable product architecture enabling rapid experimentation, evolution, and future extensibility.",
        "Personally owned product vision, system architecture, and key technical decisions while leading a multidisciplinary team."
      ]
    },
    {
      id: "frshly",
      title: "Head of Innovation (Product & Design)",
      company: "Frshly",
      location: "Chennai, India",
      period: "Jul 2017 \u2013 Nov 2018",
      type: "technical",
      summary: "Pioneered smart food dispensing systems with computer vision-driven interactions.",
      achievements: [
        "Led product innovation for smart food dispensing systems, balancing reliability, speed, and intuitive user interaction.",
        "Designed computer-vision-driven interaction flows tightly coupled with embedded hardware behavior."
      ]
    },
    {
      id: "replicant",
      title: "Technical Consultant (Product)",
      company: "Replicant Systems",
      location: "Hyderabad, India",
      period: "Sep 2024 \u2013 Oct 2024",
      type: "technical",
      summary: "Freelance product consulting for early-stage technology startups.",
      achievements: [
        "Provided freelance product management consulting for early-stage technology initiatives.",
        "Helped founders translate abstract ideas into structured problem statements, MVP definitions, and product roadmaps.",
        "Acted as a product sounding board across system architecture, feasibility analysis, and build sequencing."
      ]
    },
    {
      id: "prior",
      title: "Foundational Engineering & Systems Roles",
      company: "Various Organizations",
      location: "India & Germany",
      period: "2010 \u2013 2017",
      type: "prior",
      summary: "Built deep foundations in electro-mechanical systems and real-world manufacturing.",
      achievements: [
        "Built strong grounding in electro-mechanical systems, industrial design, and real-world manufacturing constraints \u2014 forming the basis for a first-principles product mindset.",
        "Worked across mechanical, electrical, and control systems, developing an intuitive understanding of how physical products behave outside ideal conditions.",
        "Collaborated with cross-functional teams in production, design, and field environments, shaping later strengths in system-level product architecture.",
        "Organizations: Consultant at Prikal Engineering; Electro-Mechanical Engineer at Gebr. Bode GmbH (Germany); Design Intern at Nutech Industrial; Trainee at SMA Railway Technology (Germany) and Ashok Leyland."
      ]
    }
  ],
  patents: [
    {
      title: "Food Processor Machine with Ready-to-Cook Product",
      number: "IN 365893",
      description: "End-to-end productized electromechanical system integrating automated dispensing, heating, and cooking logic."
    }
  ],
  innovations: [
    {
      title: "Computer Vision-based QR Recognition Systems",
      description: "Smart dispenser interaction system using computer vision for QR recognition."
    }
  ],
  education: [
    {
      degree: "PGDM \u2013 Product Management",
      institution: "Duke University",
      location: "USA",
      year: "2024"
    },
    {
      degree: "M.S. Mechanical Engineering (Mechatronics)",
      institution: "Link\xF6pings Universitet",
      location: "Sweden",
      year: "2015",
      highlight: "International Scholarship Finalist"
    },
    {
      degree: "B.Tech Mechatronics Engineering",
      institution: "SRM University",
      location: "India",
      year: "2013"
    }
  ],
  languages: [
    { name: "English", proficiency: "native" },
    { name: "Tamil", proficiency: "native" },
    { name: "Hindi", proficiency: "professional" },
    { name: "Swedish", proficiency: "basic" },
    { name: "German", proficiency: "basic" }
  ]
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Jaikrishnan Ganeshan's public profile: name, title, tagline, location, contact links, resume and portfolio URLs, product philosophy and languages.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const site = "https://jaikrishnan.in";
    const abs = (u) => u.startsWith("/") ? site + u : u;
    const payload = {
      personal: {
        ...portfolioData.personal,
        website: site,
        resumeUrl: abs(portfolioData.personal.resumeUrl),
        portfolioUrl: abs(portfolioData.personal.portfolioUrl)
      },
      philosophy: portfolioData.philosophy.map((p) => p.text),
      languages: portfolioData.languages
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List professional experience",
  description: "List Jaikrishnan's professional experience entries (company, role, period, summary and achievements). Optionally filter by company name.",
  inputSchema: {
    company: z.string().optional().describe("Optional case-insensitive substring to filter by company or role.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ company }) => {
    const needle = company?.trim().toLowerCase();
    const items = needle ? portfolioData.experience.filter(
      (e) => e.company.toLowerCase().includes(needle) || e.title.toLowerCase().includes(needle)
    ) : portfolioData.experience;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-capabilities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_capabilities_default = defineTool3({
  name: "list_capabilities",
  title: "List capabilities",
  description: "List Jaikrishnan's product, hardware, platform and leadership capabilities grouped by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = portfolioData.capabilities.map((c) => ({
      category: c.title,
      skills: c.skills
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/get-credentials.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_credentials_default = defineTool4({
  name: "get_credentials",
  title: "Get education, patents and innovations",
  description: "Get Jaikrishnan's education history, granted patents and notable technical innovations.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      education: portfolioData.education,
      patents: portfolioData.patents,
      innovations: portfolioData.innovations
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jaikrishnan-s-portfolio",
  title: "Jaikrishnan's Portfolio",
  version: "0.1.0",
  instructions: "Tools for exploring Jaikrishnan Ganeshan's public product portfolio. Use `get_profile` for who he is and how to reach him, `list_experience` for roles and achievements, `list_capabilities` for skills, and `get_credentials` for education, patents and innovations.",
  tools: [get_profile_default, list_experience_default, list_capabilities_default, get_credentials_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
